"""Added date metadata to ErgoJob

Revision ID: d0023e077cbc
Revises: fdba002dd748
Create Date: 2020-07-15 11:11:15.429075

"""
from alembic import op
import sqlalchemy as sa
import airflow
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0023e077cbc'
down_revision = 'fdba002dd748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ergo_job', sa.Column('created_at', airflow.utils.sqlalchemy.UtcDateTime(timezone=True), nullable=False))
    op.add_column('ergo_job', sa.Column('response_at', airflow.utils.sqlalchemy.UtcDateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_ergo_job_created_at'), 'ergo_job', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ergo_job_created_at'), table_name='ergo_job')
    op.drop_column('ergo_job', 'response_at')
    op.drop_column('ergo_job', 'created_at')
    # ### end Alembic commands ###
